(ns com.github.funkschy.jrpg.components)

(defrecord Animation [animation flip-h?])
(defrecord AnimationStateMachine [state-machine])
(defrecord Sprite [sprite w-scale h-scale layer])
(defrecord Transform [position])
(defrecord Velocity [dir speed])
(defrecord Input [delta-sum interacting?])
(defrecord InteractionContent [content]) ; a potential interaction (on the npc)
(defrecord CurrentInteraction [running? content]) ; the running interaction (on the player)
(defrecord InteractionHitbox [aabb])
(defrecord Hitbox [aabb])
